# Generated by Django 5.2.5 on 2025-08-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='user_management.instructorprofile')),
            ],
            options={
                'db_table': 'instructor_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('instructor_profile', 'day_of_week', 'start_time')},
            },
        ),
    ]
