# Generated by Django 5.2.5 on 2025-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_instructoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyprofile',
            name='academy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academyprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='academyprofile',
            name='main_postcode',
            field=models.CharField(blank=True, help_text='Main operating postcode', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academyprofile',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Main contact person', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='adi_number',
            field=models.CharField(blank=True, help_text='Approved Driving Instructor Number from DVSA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='ADI number verification status'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='postcodes',
            field=models.TextField(blank=True, help_text="Postcodes covered (e.g., 'LN1, LN2, LN5')", null=True),
        ),
    ]
