# Prometheus Configuration for DriveEver Microservices
# Monitors all services and collects metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prompt Service
  - job_name: 'prompt-service'
    static_configs:
      - targets: ['prompt-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Service
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Vehicle Service
  - job_name: 'vehicle-service'
    static_configs:
      - targets: ['vehicle-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']




